In [2]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.7.0


In [3]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimension of vector
vector.ndim

1

In [7]:
# Create a matrix (has more than 1 dimension)
matrix = tf.constant([[10, 7], [10,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [10,  7]], dtype=int32)>

In [8]:
another_matrix = tf.constant([[10., 7.], [3., 2.], [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
another_matrix.ndim

2

In [10]:
tensor = tf.constant([[[1,2,3],
                      [4,5,6]],
                     [[7,8,9],
                      [10,11,12]],
                     [[13,14,15],
                      [15,16,17]]], dtype=tf.int32)
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [15, 16, 17]]], dtype=int32)>

In [11]:
tensor.ndim

3

* Scalar: a single number
* Vector: a number with direction
* Matrix: a 2-dimensional array of numbers
* Tensor: an n-dimensional array of numbers

### Creating tensors with tf.Variable

In [12]:
#Create the same tensor with tf.Varible() as above?
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
#Changing tensors
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
#Creating random tensors, they are tensors of some arbitrary size which contain random numbers
random_1 = tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1 = random_1.normal(shape=(3,2))
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

#Are they equal?
random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

###Shuffle the order of elements in a tensor

In [15]:
# Shuffle the data so inherant order of data doesnt effect learning
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
not_shuffled.ndim
# Shuffle the not shuffled tensor, shuffles on the first dimension
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [16]:
tf.random.set_seed(5) #Global level random seed
print(tf.random.shuffle(not_shuffled, seed=42)) #Operation level random seed
print(tf.random.shuffle(not_shuffled))

tf.Tensor(
[[ 2  5]
 [ 3  4]
 [10  7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 2  5]
 [10  7]
 [ 3  4]], shape=(3, 2), dtype=int32)


Seed generation uses both a global and operational seed:
* If both seeds are not set, then sequence will be random
* If only global is set, then each call will be random, but order is repeatable for each rerun
* If only operational is set, then sequence will be the same, but different for each rerun???
* If both are set, then each call and rerun will stay constant

###Other ways to make tensors

In [17]:
#Create tensor of all 1s
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [18]:
#Create tensor of all 0s
tf.zeros(shape=(3,4), dtype=tf.float32)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

###Turn numpy arrays into tensors
Main difference between NumPy arrays and TensorFLow tensors is that tensors can be run on a GPU much faster

In [19]:
#Numpy arrays can be also turned into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

#X = tf.constant(come_matrix) #Capital for matrix or tensor
#y = tf.constant(vector #Non-capital for vector)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
#Turn array into tensor, then reshape
A = tf.constant(numpy_A, shape=(2,3,4))
B = tf.constant(numpy_A)
A, B
A.ndim

3

###Getting information from Tensors
* Shape
* Rank
* Axis or dimension
* Size

In [21]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=(2,3,4,5), dtype=tf.int32)
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=int32, numpy=
array([[[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]],

        [[0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [0, 0, 0, 0, 0]]]], dtype=int32)>

In [22]:
print(rank_4_tensor.shape, #shape = (2, 3, 4, 5)
rank_4_tensor[0][1][1][1], #index = tf.Tensor(0, shape=(), dtype=int32)
rank_4_tensor.ndim, #dimension = 4
tf.size(rank_4_tensor)) #size = 2*3*4*5

(2, 3, 4, 5) tf.Tensor(0, shape=(), dtype=int32) 4 tf.Tensor(120, shape=(), dtype=int32)


In [23]:
#Get various attributes of our tensor
print("Datatype of every elemetn: ", rank_4_tensor.dtype)
print("Number of dimensions (rank): ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Elements along the 0 axis: ", rank_4_tensor.shape[0])
print("Elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every elemetn:  <dtype: 'int32'>
Number of dimensions (rank):  4
Shape of tensor:  (2, 3, 4, 5)
Elements along the 0 axis:  2
Elements along the last axis:  5
Total number of elements in our tensor:  120


###Indexing Tensors

In [24]:
#Get the first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int32, numpy=
array([[[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0]]]], dtype=int32)>

In [25]:
rank_4_tensor[:1, :1, :1, :] #All values of the first list, in the first row, in the first matrix


<tf.Tensor: shape=(1, 1, 1, 5), dtype=int32, numpy=array([[[[0, 0, 0, 0, 0]]]], dtype=int32)>

In [26]:
rank_4_tensor[:1, :1, :, :1] #first element of all rows in the matrix

<tf.Tensor: shape=(1, 1, 4, 1), dtype=int32, numpy=
array([[[[0],
         [0],
         [0],
         [0]]]], dtype=int32)>

In [27]:
rank_4_tensor[:,:,:,-1:] #last element in each dimension

<tf.Tensor: shape=(2, 3, 4, 1), dtype=int32, numpy=
array([[[[0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [0]]],


       [[[0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [0]],

        [[0],
         [0],
         [0],
         [0]]]], dtype=int32)>

In [28]:
#rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
#last element in each row of tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [29]:
#Add in extra dimenion to the rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [30]:
#Alternative
tf.expand_dims(rank_2_tensor, axis = -1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [31]:
tf.expand_dims(rank_2_tensor, axis = 0) # expands on the 0th axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

###Tensor Operations


In [32]:
#Addition
tensor = tf.constant([[10, 7], 
                      [3, 4]])
tensor + 10 #original tensor is unchanged however

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [33]:
#Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [34]:
#Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [35]:
# Using tensorflow library, it usually is faster than arithmetic 
tf.multiply(tensor, 10) #gets same 
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

###Matrix Multiplication

In [36]:
#Matrix dot multiplication
tf.matmul(tensor,tensor)
#Or
tf.tensordot(tensor, tensor, axes = 1) #dot product is on 1

#axes = 0 : tensor product 

#axes = 1 : tensor dot product 

#axes = 2 : (default) tensor double contraction 



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [37]:
m1 = tf.constant([[1,2,5],
                  [7,2,1],
                  [3,3,3]])
m2 = tf.constant([[3,5],
                  [6,7],
                  [1,8]])
tf.matmul(m1,m2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [38]:
# @ is the python operator for matrix muliplication
tensor@tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [39]:
# matrix reshape and transpose
tf.reshape(tensor, shape = [4,1])
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 7,  4]], dtype=int32)>

###Changing Data type of tensor

In [40]:
#Create a new tensor with default datatype (float32)
B = tf.constant([1.7,1.4])
B.dtype

tf.float32

In [41]:
C = tf.constant([7,10])
C.dtype

tf.int32

In [42]:
#Change from float32 to float16, reduce precision
D = tf.cast(B, dtype = tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 1.4], dtype=float16)>,
 tf.float16)

In [43]:
#Change from int32 to float16
E = tf.cast(C, dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

###Aggregating tensors

Aggregating tensors = condensing them from mulitple values to a smaller amount of values

In [44]:
#Getting the absolute values (not the best method)
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [45]:
#Get te absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Other forms of aggregation:
* Get the min
* Get the max
* Get the mean 
* Get the sum

In [46]:
D = tf.constant([[1,2],
                 [5,8] ])
print(tf.reduce_max(D))
print(tf.reduce_min(D))
print(tf.reduce_mean(D))
print(tf.reduce_sum(D))
E = tf.cast(D, dtype = tf.float16)
print(tf.math.reduce_std(E)) #standard deviation must use float
print(tf.math.reduce_variance(E, axis = 0))

tf.Tensor(8, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(16, shape=(), dtype=int32)
tf.Tensor(2.738, shape=(), dtype=float16)
tf.Tensor([4. 9.], shape=(2,), dtype=float16)


In [47]:
#Alternate use
import tensorflow_probability as tfp
tfp.stats.variance(E) #Can take integer. Needs tfp library. Automatically uses axis = 0

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([4., 9.], dtype=float16)>

Short note on axes:

Axis are different directions to look at a matrix. The number of prespectives matches the dimensions of the matrix looked at. Remember it is like the MRI example!
* 0 = looking at the whole matrix (or number)
* 1 = looking at it from the column perspective/top down/bottom up
* 2 = looking at it from the row perspective/left to right/right to left perspective 


###Find the positional max and min

In [48]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [49]:
#Find the positional maximum
print(tf.argmax(F)) #Same as np.argmax()
print(F[42])

print(tf.argmin(F))
print(F[16])

tf.Tensor(42, shape=(), dtype=int64)
tf.Tensor(0.9671384, shape=(), dtype=float32)
tf.Tensor(16, shape=(), dtype=int64)
tf.Tensor(0.009463668, shape=(), dtype=float32)


###Squeezing a tensor (removing all single dimensions)

In [50]:
#Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,50))
print(G)
F = tf.constant([[],
                 [2,4]]) #Makes a shape of [2, 0] which is weird
F.shape

tf.Tensor(
[[[[[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
     0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
     0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
     0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
     0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
     0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
     0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
     0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
     0.7381023  0.32054043]]]]], shape=(1, 1, 1, 1, 50), dtype=float32)


TensorShape([2, 0])

In [51]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [52]:
#Squeezing G, reduces dimensions of size 1
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

###One-hot encoding tensors
* a way to make things into numbers

In [53]:
#Create a list of indicies
some_list = [0, 1, 2, 2] #could be red, green, blue, purple

#One hot encode our list of indicies
tf.one_hot(some_list, depth = 4) #depth must be equal to variables represented
#extra depth will add columns but not rows

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.]], dtype=float32)>

In [ ]:
#Specify custom values for one hot encoding
tf.one_hot(some_list, depth = 4, on_value="on", off_value="off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

#Other math functions

* tf.sqrt() must be specific dtypes, such as float
* tf.square()
* tf.math.log() must be specific dtypes


###Tensors and NumPy

TensorFlow interacts beautifully with NumPy arrays

In [ ]:
#Create tensor from array
J = tf.constant(np.array([3. ,7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back into Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
#The default type of each are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

#Check the datatype of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)